### ISSUE TITLE
Stock Split is not working for ETFs

### ISSUE THREAD

**Issue by maheshgune** [NSEDownload/NSEDownload#11]
Hello,

While ETFs are treated like a stock as far as providing the data using the command is concerned, it does not provide split adjusted data. 

E.g. NIFTYBEES and GOLDBEES have split sometime back, the data previous to that is not adjusted for split. 

Possible to look into it?

**Comment by jinit24** [comment]
Hi @maheshgune,

So the corporate actions are scraped from [link](https://www1.nseindia.com/corporates/corporateHome.html?id=eqCorpActions&radio_btn=company&param=NIFTYBEES). This works only for companies, you can try changing the company name field on the link and you'll see no matches appear for niftybees or Nippon or ETF.  We'll have to look at something else for adjusting data. Open to your suggestions
