### ISSUE TITLE
not getting proper data..

### ISSUE THREAD

**Issue by maheshgune** [NSEDownload/NSEDownload#13]
I need to download Nifty 500 Data every Friday evening. I already have a program in Yfinance. 

I was planning to migrate from Yfinance to NSEDownload and modified the program. However I have following issues and impression about the library as I started using it more.

1) I am not sure, if full data right from day one is downloaded by library and only that data is presented which has been asked. 

2) This stems from the fact that while I have asked data for previous year, it downloads the bonus and split history from 2010.  So everything is downloaded and then split bonus executed and data is presented thereafter.

3) For few scrips data is not downloaded properly. For example - JSWENERGY.  Data is not downloaded from 2021-07-28, not sure why. There are few more scrips for which data is missing for dates in between start and end dates.

Kindly look into the issues.

**Comment by jinit24** [comment]
Hi @maheshgune,
For JSWENERGY, the site doesn't have the data. The last date which has data is 7-28-2021 if you change the range below to 365 days.
<img width="644" alt="image" src="https://user-images.githubusercontent.com/45783917/161821203-df68aee1-7ad5-4ff7-a058-4ba46c28501b.png">

For the first 2, can you share a screenshot or code link? It'll be easier to debug if there's a specific example.

**Comment by maheshgune** [comment]
You are getting this result because you are looking at EQ Series. This script is in BE - Trade to Trade Segment. 

![JSWENERGY](https://user-images.githubusercontent.com/96491346/161952488-7f15c8a0-bc28-4ae2-8ecb-0a13976608d2.jpg)

I will update on other two issues once I run my weekly program.(Will also run modified program based on this library.)

**Comment by maheshgune** [comment]
Here is the first clue.

In [297]: start
Out[297]: '2021-04-11'

In [298]: end
Out[298]: '2022-04-11'

In [299]: f = stocks.get_adjusted_stock(stockSymbol = 'RELIANCE', start_date =start, end_date = end, check_stockSymbol=False)
BONUS  on :  07-Sep-2017  and ratio is :  2.0

I have asked for data between 11 April of last year and 11 April of this year. But it is still showing bonus for year 2017.

That gives me impression that data is fully loaded since 201x then bonus/split if any is applied.

**Comment by maheshgune** [comment]
And Try ADANITRANS. This scrip moved from EQ to BE series. Sometime in June 2021. So while scrip in BE series, it wont display data like above JSWENERGY.  This needs a look.

**Comment by maheshgune** [comment]
https://www.tickertape.in/blog/nse-stock-series-what-do-they-mean-and-which-category-is-for-you/   

This link will give you details of market segments. But for normal purpose EQ and BE should be sufficient in your code.

Thanks.

**Comment by maheshgune** [comment]
If you are modifying the library, then kindly allow library to fetch data of all series. So there wont be any issues.  Because real estate (REIT) are in RR series. And it can be one asset class, specially when inflation is flaring up.

https://www.nseindia.com/market-data/legend-of-series

Another good link to various series of NSE marketplace.

**Comment by kanishk619** [comment]
You can change the series argument to ALL and then filter the dataframe. Valid series are 
[
        'ALL', 'BE', 'BL', 'BT', 'BZ', 'D1', 'D2', 'D3', 'DR', 'E1', 'E2', 'E3', 'E4', 'E5', 'EQ', 'GC', 
        'IL', 'K1', 'M1', 'MF', 'N1', 'N2', 'N3', 'N4', 'N5', 'N6', 'N7', 'N8', 'N9', 'NA', 'NB', 'NC', 'ND', 'NE', 
        'NF', 'NG', 'NH', 'NI', 'NJ', 'NK', 'NL', 'NM', 'NN', 'NO', 'NP', 'NR', 'NS', 'NT', 'NU', 'NQ', 'O1', 'O2', 
        'O3', 'O4', 'O5', 'O9', 'P1', 'P2', 'P3', 'P4', 'Q1', 'Q2', 'RL', 'U1', 'U2', 'U3', 'U4', 'U5', 'U6', 'U7', 
        'U8', 'UB', 'UX', 'UY', 'UZ', 'W1', 'W2', 'YB', 'YO', 'YP', 'GB', 'IV', 'ID', 'IA'
    ]

**Comment by jinit24** [comment]
@kanishk619 thanks for the suggestion. Need to change Series=All in the URL to allow different series types. We can probably take a specific type as input as well and by default keep its value EQ. 

**Scraper.py**
```python
        if(type == 'stock'):
            final_url = get_symbol_mapping_url() + '?symbol=' + stockSymbol + '&segmentLink=3&symbolCount' + symbolCount + "&series=EQ&dateRange=+&fromDate=" + \
                start_date.strftime(
                    "%d-%m-%Y")+"&toDate="+end_date.strftime("%d-%m-%Y")+"&dataType=PRICEVOLUMEDELIVERABLE"
```

@maheshgune, what are your thoughts on this idea?

**Comment by maheshgune** [comment]
Most of equities for which user want to access data is in EQ Series and BE series. If we can make this as default, it will be good. 

Because making EQ series as default, will leave BE series scrip without any data. And depending upon SEBI's ASM model scrips keeps moving from EQ to BE series. This is biggest challenge. It will be bugging for users to keep shifting series in program.

So better option can be "all" = EQ or BE, "All" = all other series.  Something like this. 

I know this can be challenging to code but still.

Regards.

**Comment by maheshgune** [comment]
One more suggestion - Will it be possible for you to suppress Split and Bonus messages? They are internal to command. Will be helpful.

**Comment by tsdev-we** [comment]
ABBOTINDIA is also missing through API but but NSE site show them

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_1662766/936836961.py in <module>
----> 1 df = stocks.get_data(stockSymbol = "ABBOTINDIA", start_date = '2-7-2021', end_date = '7-8-2022')

~/anaconda3/lib/python3.9/site-packages/NSEDownload/stocks.py in get_data(stockSymbol, full_data, start_date, end_date, check_stockSymbol)
     55 
     56     if(check_stockSymbol is True):
---> 57         check_name(stocks_values, stocks_values, stockSymbol)
     58 
     59     stockSymbol = stockSymbol.replace('&', '%26')

~/anaconda3/lib/python3.9/site-packages/NSEDownload/check.py in check_name(arr, values, name)
     32 
     33     if(flag == 0):
---> 34         raise ValueError(
     35             "Please check symbol provided. Try {} as name.".format(maxVal))

ValueError: Please check symbol provided. Try WABCOINDIA as name.

**Comment by maheshgune** [comment]
Any idea when latest version will be available for testing / use?

**Comment by jinit24** [comment]
@tsdev-we, you can use 
```python
from NSEDownload import stocks
df = stocks.get_adjusted_stock(stockSymbol = 'ABBOTINDIA', start_date = '2-7-2021', end_date = '7-8-2022', check_stockSymbol=False)
```

**Comment by jinit24** [comment]
> @tsdev-we, you can use
> 
> ```python
> from NSEDownload import stocks
> df = stocks.get_adjusted_stock(stockSymbol = 'ABBOTINDIA', start_date = '2-7-2021', end_date = '7-8-2022', check_stockSymbol=False)
> ```

**Comment by jinit24** [comment]
Hi @maheshgune, 
I have made a few changes to allow all series, I shall push them soon.

**Comment by maheshgune** [comment]
Thanks..
.
,
Egarly waiting..

**Comment by jinit24** [comment]
@maheshgune, please take a look at the [new branch](https://github.com/NSEDownload/NSEDownload/tree/new_series_feature) and install it. Use the new parameter series and set it to all. Currently, it only takes a string value.
```python
df = stocks.get_data(stockSymbol = 'RELIANCE', start_date = '15-9-2021', end_date = '1-10-2021', series="ALL")

```

**Comment by maheshgune** [comment]
Sorry. Saw this message today only. Just check for IIFL. Saw some data  which shows it has more than 10 series. (Besides EQ, some series related to N.) There are couple of scrips where trading happens for more than one series. Important data is for EQ and BE series.

**Comment by maheshgune** [comment]
Tried to install. But got following error.

In [264]: pip install NSEDownload/dist/*
ERROR: Invalid requirement: 'NSEDownload/dist/*'

I am using Anaconda.

**Comment by maheshgune** [comment]
Finally Installed.

In [585]: pip install NSEDownload-4.1.6.tar.gz
Processing c:\users\yogeeta\nsedownload-4.1.6.tar.gz
Requirement already satisfied: beautifulsoup4 in c:\users\yogeeta\anaconda3\lib\site-packages (from NSEDownload==4.1.6) (4.9.3)
Requirement already satisfied: requests in c:\users\yogeeta\anaconda3\lib\site-packages (from NSEDownload==4.1.6) (2.25.1)
Requirement already satisfied: pandas in c:\users\yogeeta\anaconda3\lib\site-packages (from NSEDownload==4.1.6) (1.2.4)
Requirement already satisfied: numpy in c:\users\yogeeta\anaconda3\lib\site-packages (from NSEDownload==4.1.6) (1.20.1)
Requirement already satisfied: timedelta in c:\users\yogeeta\anaconda3\lib\site-packages (from NSEDownload==4.1.6) (2020.12.3)
Requirement already satisfied: fuzzywuzzy in c:\users\yogeeta\anaconda3\lib\site-packages (from NSEDownload==4.1.6) (0.18.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\yogeeta\anaconda3\lib\site-packages (from beautifulsoup4->NSEDownload==4.1.6) (2.2.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\yogeeta\anaconda3\lib\site-packages (from pandas->NSEDownload==4.1.6) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\yogeeta\anaconda3\lib\site-packages (from pandas->NSEDownload==4.1.6) (2.8.1)
Requirement already satisfied: six>=1.5 in c:\users\yogeeta\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas->NSEDownload==4.1.6) (1.15.0)
Requirement already satisfied: idna<3,>=2.5 in c:\users\yogeeta\anaconda3\lib\site-packages (from requests->NSEDownload==4.1.6) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\yogeeta\anaconda3\lib\site-packages (from requests->NSEDownload==4.1.6) (3.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\yogeeta\anaconda3\lib\site-packages (from requests->NSEDownload==4.1.6) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\yogeeta\anaconda3\lib\site-packages (from requests->NSEDownload==4.1.6) (2020.12.5)
Building wheels for collected packages: NSEDownload
  Building wheel for NSEDownload (setup.py) ... done
  Created wheel for NSEDownload: filename=NSEDownload-4.1.6-py3-none-any.whl size=22520 sha256=b4281fc78e8fe6d546cef5286a30dbabc878ae38e3bc08ffda8e7db533c8cd2f
  Stored in directory: c:\users\yogeeta\appdata\local\pip\cache\wheels\76\c7\45\6ad62675ee4687795955e9c008829e52a57fd98df9f7ea0b86
Successfully built NSEDownload
Installing collected packages: NSEDownload
  Attempting uninstall: NSEDownload
    Found existing installation: NSEDownload 4.1
    Uninstalling NSEDownload-4.1:
      Successfully uninstalled NSEDownload-4.1
Successfully installed NSEDownload-4.1.6
Note: you may need to restart the kernel to use updated packages.

**Comment by maheshgune** [comment]
First observation - Good improvement about stock split and bonus as it is internal to command.

Tested for JSWENERGY as mentioned above.

Here is the output.

 In [8]: df = stocks.get_data(stockSymbol = 'JSWENERGY', start_date = '15-9-2011', end_date = '22-08-2022', series="ALL")
JSWENERGY

In [10]: df['2022-01-01':]
Out[10]:
               Symbol Series  Prev Close  Open Price  High Price  ...      Turnover  No. of Trades  Deliverable Qty  % Dly Qt to Traded Qty
Date                                                              ...
2022-01-03  JSWENERGY     BE      300.50      305.00      305.70  ...  3.090419e+08           6958                -                       -
2022-01-04  JSWENERGY     BE      299.00      298.00      304.80  ...  2.984092e+08           6175                -                       -
2022-01-05  JSWENERGY     BE      303.20      304.20      305.00  ...  4.527312e+08           6353                -                       -
2022-01-06  JSWENERGY     BE      295.90      292.05      303.00  ...  1.064623e+08           5054                -                       -
2022-01-07  JSWENERGY     BE      299.75      305.10      309.50  ...  1.926466e+08           7564                -                       -
...               ...    ...         ...         ...         ...  ...           ...            ...              ...                     ... ..
2022-08-16  JSWENERGY     EQ      320.05      321.70      335.75  ...  6.804092e+08          28632           748435                   35.98
2022-08-17  JSWENERGY     EQ      333.55      334.50      342.00  ...  6.174263e+08          27959           911935                   49.52
2022-08-18  JSWENERGY     EQ      332.20      332.95      334.40  ...  4.330682e+08          18695           679275                   51.14
2022-08-19  JSWENERGY     EQ      326.90      326.50      328.55  ...  3.196019e+08          15394           530738                   53.13
2022-08-22  JSWENERGY     EQ      316.20      312.00      315.50  ...  2.831651e+08          15960           473599                   51.45

[158 rows x 15 columns]

Excellent. This shows scrip was in BE segment and moved to EQ.

Will test on few more scrips, then modify the weekly program for testing.

Thanks again for the efforts.

**Comment by maheshgune** [comment]
Here is another output where a scrip is traded for multiple series. Stock name Britannia.

In [12]: df = stocks.get_data(stockSymbol = 'BRITANNIA', start_date = '15-9-2021', end_date = '22-08-2022', series="ALL")
BRITANNIA

In [13]: df
Out[13]:
               Symbol Series  Prev Close  Open Price  High Price  ...      Turnover  No. of Trades  Deliverable Qty  % Dly Qt to Traded Qty
Date                                                              ...
2021-09-15  BRITANNIA     EQ     4101.50     4105.20     4135.00  ...  8.940743e+08          27351           102946                   47.19
2021-09-15  BRITANNIA     N2       31.04       30.25       31.10  ...  8.071576e+04             63             2589                   99.46
2021-09-15  BRITANNIA     N3       29.65       29.60       29.68  ...  1.359914e+06            430            45805                   99.81
2021-09-16  BRITANNIA     N3       29.62       29.62       29.68  ...  1.268778e+06            241            42785                   99.98
2021-09-16  BRITANNIA     EQ     4086.35     4086.35     4120.00  ...  9.915379e+08          39433           130976                   53.76
...               ...    ...         ...         ...         ...  ...           ...            ...              ...                     ... ..
2022-08-18  BRITANNIA     N3       28.34       28.28       28.50  ...  1.350463e+05            115             4764                  100.00
2022-08-19  BRITANNIA     EQ     3693.05     3693.05     3709.45  ...  6.518395e+08          17676            80957                   45.49
2022-08-19  BRITANNIA     N3       28.43       28.33       29.00  ...  1.871391e+05            110             6450                   97.77
2022-08-22  BRITANNIA     EQ     3662.55     3662.55     3733.00  ...  1.353928e+09          32639            77301                   21.10
2022-08-22  BRITANNIA     N3       28.36       28.88       28.88  ...  5.486290e+04            100             1641                   84.89

In the following command, I specifically tried EQ series and output is correct.

In [14]: df = stocks.get_data(stockSymbol = 'BRITANNIA', start_date = '15-9-2021', end_date = '22-08-2022', series="EQ")
BRITANNIA

In [15]: df
Out[15]:
               Symbol Series  Prev Close  Open Price  High Price  ...      Turnover  No. of Trades  Deliverable Qty  % Dly Qt to Traded Qty
Date                                                              ...
2021-09-15  BRITANNIA     EQ     4101.50     4105.20     4135.00  ...  8.940743e+08          27351           102946                   47.19
2021-09-16  BRITANNIA     EQ     4086.35     4086.35     4120.00  ...  9.915379e+08          39433           130976                   53.76
2021-09-17  BRITANNIA     EQ     4073.05     4077.40     4115.00  ...  2.523346e+09          27336           479581                   77.16
2021-09-20  BRITANNIA     EQ     4051.85     4035.00     4115.00  ...  1.189839e+09          24488           105428                   36.22
2021-09-21  BRITANNIA     EQ     4084.50     4062.20     4111.55  ...  1.729491e+09          24140           313376                   73.86
...               ...    ...         ...         ...         ...  ...           ...            ...              ...                     ... ..
2022-08-16  BRITANNIA     EQ     3659.75     3678.05     3723.95  ...  8.852163e+08          25228            85392                   35.65
2022-08-17  BRITANNIA     EQ     3690.45     3693.00     3714.95  ...  1.310574e+09          35942           200477                   56.64
2022-08-18  BRITANNIA     EQ     3705.20     3712.00     3726.95  ...  8.597314e+08          23772           117278                   50.49
2022-08-19  BRITANNIA     EQ     3693.05     3693.05     3709.45  ...  6.518395e+08          17676            80957                   45.49
2022-08-22  BRITANNIA     EQ     3662.55     3662.55     3733.00  ...  1.353928e+09          32639            77301                   21.10

But it is not a big problem, we will have to select data based on EQ and BE series. 

That will solve problem.

**Comment by maheshgune** [comment]
I guess this is the solution.

df = df[(df['Series']=='EQ') | (df['Series']=='BE')]

**Comment by maheshgune** [comment]
Now I will have to update my stock prices collection program which runs on weekly basis, mostly on week end.

Once I modify and run it, I will let you know.

It has to run Nifty 500 /Nifty Total Market stocks (which is around 750)

**Comment by maheshgune** [comment]
Check fist iteration. Following observation.

1) Works neatly.

2) Initially it gave some problem of Time out (20 seconds). Then modified one of .py file of NSEDownload and increased one zero. Then it started working properly, I guess. Still needs some more testing.

3) A scrip name PCBL (earlier scrip name - PHILIPCARB) is giving result using NSE web site (www1.nseindia.com/...)  but through this library it is giving problem, even though used check_stockSymbol=False

4) Follwing scrip do not return any data at NSE websit(www1.nseindia.com) so no question of this library returning any data. 
    RBA, EQUITASBNK, GLAND, HOMEFIRST, KALYANKJIL, MAZDOC, UNOMINDA (earlier MINDAIND), EASEMYTRIP

**Comment by maheshgune** [comment]
Facing following issue since morning..
.
,
Processing Scrip_nd: AAVAS
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\yogeeta\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\yogeeta\anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\yogeeta\anaconda3\lib\site-packages\NSEDownload\scraper.py", line 45, in worker_thread
    df = pd.read_csv(str(stage) + ".csv")
  File "C:\Users\yogeeta\anaconda3\lib\site-packages\pandas\io\parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\yogeeta\anaconda3\lib\site-packages\pandas\io\parsers.py", line 468, in _read
    return parser.read(nrows)
  File "C:\Users\yogeeta\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "C:\Users\yogeeta\anaconda3\lib\site-packages\pandas\io\parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas\_libs\parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas\_libs\parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas\_libs\parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas\_libs\parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas\_libs\parsers.pyx", line 1951, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 16 fields in line 204, saw 23
.
.
I guess NSEDownload generate a file 0.csv. In this file, there is one line which is not correct and that is where it is giving error. Suddenly column header appears instead of data. The data at NSE is cleaned. I checked by downloading the data into xl file for same period as my program( one year.) So look like this library issue.

**Comment by maheshgune** [comment]
Above problem came due to NSE web site. After multiple iteration, it went well. FYI.

**Comment by jinit24** [comment]
> Check fist iteration. Following observation.
> 
> 1. Works neatly.
> 2. Initially it gave some problem of Time out (20 seconds). Then modified one of .py file of NSEDownload and increased one zero. Then it started working properly, I guess. Still needs some more testing.
> 3. A scrip name PCBL (earlier scrip name - PHILIPCARB) is giving result using NSE web site (www1.nseindia.com/...)  but through this library it is giving problem, even though used check_stockSymbol=False
> 4. Follwing scrip do not return any data at NSE websit(www1.nseindia.com) so no question of this library returning any data.
>    RBA, EQUITASBNK, GLAND, HOMEFIRST, KALYANKJIL, MAZDOC, UNOMINDA (earlier MINDAIND), EASEMYTRIP

@maheshgune,
1. I shall take look at the scrips mentioned in 3,4. 
2. We should probably add some **stress tests and efficiency tests**. It might be interesting to think of how to do the former. Let me know your ideas. The issue with requests is that they are erratic. Sometimes they might work, sometimes they won't. Sometimes the response can take too long. Need to find a **better way to retry missed requests**.
3. Yep, we can increase the **timeout**.

**Comment by maheshgune** [comment]
Stress test is a good option. But this is option of older system, extended still. In olden days, all component of testing system was within same premises. Like say DB server, network, client.  So stress testing will give proper result. Now in today's scenarios, we have three variables, e.g. end user device, end user connectivity and main third party system on web. Now out of these three two are beyond our control. So what ever stress testing will do , will it bear consistent result or not, will be million dollar question. Again I guess, the library uses connection-less protocol. Meaning no hand shake between client and server. So it is dependent on servers response and NSE being a public web site, the response can be erratic for their own data maintenance schedule and other parties in globe loading NSE server with their request. And I am sure NSE would have prioritized response for paid users. Having said this, stress test can be give varying result in my opinion. 

Coming to efficiency testing - my field of test is quite limited. However as this library will be getting used in future and more and more people start using it, it will give you a good feel about how efficient the library is based on the number of bugs they raise. I will try to use this in more of my different programs and check. I have also referred your library on our slack channel.  Fortunately there are less number of people who dabble python and stock market both.  A few do.

**Comment by jinit24** [comment]
@maheshgune,
Thank you so much. I have added retries and backoff in the new commit. It does seem a lot better. Let me know after your weekend run. Hopefully, more and more people use it and it actually helps them.

Just another idea. How do you run your code? If its like a jupyter notebook, then we can probably add it as an example.. How people can actually use it from start to finish. If you like the idea raise a PR. We can discuss it there. Till then I shall mark this as done.
