### ISSUE TITLE
Addition of ETFs to the Stocks List static data

### ISSUE THREAD

**Issue by FingonCelebrindal** [NSEDownload/NSEDownload#15]
Can you please add the ETFs to the static data. 
Even better if the static data can be updated from 
https://www1.nseindia.com/corporates/content/securities_info.htm

**Comment by jinit24** [comment]
Hi @FingonCelebrindal,
You can download ETFs. I'll use MOTILAL OSWAL NASDAQ Q 50 ETF (MONQ50) as an example. You can go through main page for installation, then run the following command

```python
from NSEDownload import stocks
df = stocks.get_adjusted_stock(stockSymbol = 'MONQ50', full_data=True, check_stockSymbol=False)
```

Use the check_stockSymbol=false option to prevent checking against static stock names. The output will look like this: (truncated)

| Date                | Symbol   | Series   |   Open Price |   High Price |   Low Price |   Last Price |   Close Price |   Average Price |   Total Traded Quantity |         Turnover |   No. of Trades |   Deliverable Qty |   % Dly Qt to Traded Qty |     |
|:--------------------|:---------|:---------|-------------:|-------------:|------------:|-------------:|--------------:|----------------:|------------------------:|-----------------:|----------------:|------------------:|-------------------------:|:----|
| 2021-12-29 00:00:00 | MONQ50   | EQ       |        66    |        73.99 |       66    |        66.5  |         66.94 |           68.42 |                   58233 |      3.98405e+06 |             532 |             36572 |                    62.8  |     |
| 2022-05-11 00:00:00 | MONQ50   | EQ       |        50    |        50.49 |       49.1  |        49.7  |         49.8  |           49.53 |                    7526 | 372753           |             132 |              6633 |                    88.13 |     |
| 2022-05-12 00:00:00 | MONQ50   | EQ       |        50.8  |        50.8  |       46.61 |        47.8  |         47.23 |           47.51 |                   60419 |      2.87053e+06 |             502 |             55924 |                    92.56 |     |
| 2022-05-13 00:00:00 | MONQ50   | EQ       |        48    |        49.63 |       48    |        49.5  |         48.71 |           48.58 |                   16364 | 794979           |             165 |             11900 |                    72.72 |     |


Using the site for updating static data is an exciting idea. We'll have to think of a way to update it in the background or every time we run a command, make this additional call. How would you prefer it?
