### ISSUE TITLE
Addition of TRI data into the index list

### ISSUE THREAD

**Issue by abhishanand-git** [NSEDownload/NSEDownload#17]
Currently we get Nifty 50 index data, along with that it will be useful to have Nifty 50 TRI data also. As most of the mutual funds are compared against the TRI values.

**Comment by jinit24** [comment]
You can use `indextype='TRI'` for indices. 
```python
from NSEDownload import indices
df = indices.get_data(indexName = 'NIFTY 50', full_data=True, indextype="TRI")
```
Check out the documentation for more details: https://nsedownload.github.io/NSEDownload/indices.html
