### ISSUE TITLE
Historic data of equities is missing for 1st, 2nd, Nov

### ISSUE THREAD

**Issue by manojec054** [NSEDownload/NSEDownload#23]
I observed that historical data for any equities is missing for Nov 1st, 2nd, 2022. 

API used `stocks.get_data`

Initial analysis: The same day data is missing in NSE official website as well. I already given feedback in NSE website but not sure how much serious they consider that.

![image](https://user-images.githubusercontent.com/51470228/200053562-69c7057c-0900-4ac3-9c05-eabd98807fd4.png)

**Comment by jinit24** [comment]
If it's not on the official website, it won't show up in the data.

**Comment by jinit24** [comment]
If it's not on the official website, it won't show up in the data.
