### ISSUE TITLE
This module gives live data or not

### ISSUE THREAD

**Issue by PARKER-X** [NSEDownload/NSEDownload#25]
I have  a project idea i need live data of stock prices and i want to make life virtual simulation game in python so i need live data if you know about any library that give life data of indian companies share price plz inform me.

**Comment by jinit24** [comment]
Can you elaborate on live data? Minute-wise access? 
Currently, this library doesn't do that. You can fetch daily data at EOD.

I'll let you know if I find a library for real time data
