### ISSUE TITLE
NSE has changed the data respository

### ISSUE THREAD

**Issue by maheshgune** [NSEDownload/NSEDownload#28]
Hi,

It look like NSE has changed the data repository. The data is not available at older location. Giving following error.

**W.e.f 01-April-2023, our old website ([www1.nseindia.com](http://www1.nseindia.com/)) shall not be available.

All the information which was accessible on old website has been advanced to the new website for our esteemed patrons convenience.**

Look like the library needs to be updated with latest path as it is failing to fetch data from NSE web site.

Regards,

Mahesh

**Comment by maheshgune** [comment]
While the data is not available at www1.nseindia.com, it is also not available at www.nseindia.com as well.

**Comment by SpiritStack** [comment]
+1 code broken

**Comment by scparsawar** [comment]
@jinit24 are you looking into this? maybe it will help to know if you're already working on the fix

NSE repo is not working for me as well

**Comment by jinit24** [comment]
The old site is discontinued. But the new site has authentication and can't access the API directly. So, changing the URL won't work.

**Comment by vishalvicky777** [comment]
@jinit24 are you working on this issue to get the details from new url?

**Comment by virajkadam** [comment]
can you share the new site, maybe we can contribute or explore solutions alongside.

**Comment by jinit24** [comment]
@virajkadam, @vishalvicky777, @maheshgune, @vikash-sharma-php, @scparsawar 
1. We'll have to use cookies for requests:
```python
import requests

def get_adjusted_headers():
    return {
        'Host': 'www.nseindia.com',
        'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0',
        'Accept': '*/*',
        'Accept-Language': 'en-US,en;q=0.5',
        'Accept-Encoding': 'gzip, deflate, br',
        'X-Requested-With': 'XMLHttpRequest',
        'DNT': '1',
        'Connection': 'keep-alive',
    }


session = requests.Session()
response = session.get('https://www.nseindia.com/', timeout=15, headers=get_adjusted_headers())
print(session.cookies.get_dict())

response2 = session.get(
    'https://www.nseindia.com/api/historical/cm/equity?symbol=RELIANCE&series=[%22EQ%22]&from=15-03-2022&to=15-04-2023',
    headers=get_adjusted_headers(),
    timeout=15,
    cookies=session.cookies.get_dict())

print(response2.cookies)
print(response2.status_code)
``` 

2. The API now seems to limit the response to at max 50 entries. So, even if you select a year's date range, only 50 latest are returned.

Open to PRs for the same.

**Comment by jinit24** [comment]
Check https://github.com/NSEDownload/NSEDownload/tree/jshah-fix-nse-url

**Comment by maheshgune** [comment]
Most likely the output of the command displays only 50 lines. Hence it look like that way. 

if more than 50, then one need to download csv file. So if page length can be increased to say 300,  or if we can download csv file, that would be helpful.

**Comment by alloc7260** [comment]
Use this insted : [NSE-HISTORY-SCRAPER](https://github.com/alloc7260/NSE)

**Comment by Mridul-Gulati** [comment]
> Check https://github.com/NSEDownload/NSEDownload/tree/jshah-fix-nse-url

I tried it too, still facing the "system exceed 30 redirects" error. Is it working for someone?

**Comment by jinit24** [comment]
Checkout the new master @Mridul-Gulati @maheshgune @alloc7260 @vikash-sharma-php @virajkadam
