### ISSUE TITLE
Stock data is not normalized for stock split

### ISSUE THREAD

**Issue by amirsultan** [NSEDownload/NSEDownload#3]
Is there a way to get normalized data for stock split. For example in below instance:

![image](https://user-images.githubusercontent.com/5102693/103165382-9d28b500-47dc-11eb-8be1-67e045473b40.png)

**Comment by jinit24** [comment]
I don't think that'll be possible currently. This just scrapes data. Normalizing splits will require extra information regarding the event of split and split ratio.

**Comment by jinit24** [comment]
I'm working on this. There might be a few bugs but check this out : [3.1](https://github.com/NSEDownload/NSEDownload/tree/3.1)

**Comment by viksh98** [comment]
Hey

> I'm working on this. There might be a few bugs but check this out : [3.1](https://github.com/NSEDownload/NSEDownload/tree/3.1)



> I don't think that'll be possible currently. This just scrapes data. Normalizing splits will require extra information regarding the event of split and split ratio.

Hey, I think rather than scraping company record data from text etc. you could just make adjustments using daily returns from your "returns" function. for e.g. if the one of the day return is = - 0.5, it might imply the stock has split to 1:2 that day. At least this is what I do when I collect historical data to calc std dev.

**Comment by jinit24** [comment]
That's an interesting idea. I think it'll be difficult to differentiate between an actual drop in price and a stock split. It seems unlikely that a stock would drop 33% or 50% in a day but not sure if we can rule it out completely.

**Comment by amirsultan** [comment]
Here money control places split data. We can take one-time dump and import it. What say?
https://www.moneycontrol.com/stocks/marketinfo/splits/index.php

**Comment by jinit24** [comment]
> Here money control places split data. We can take one-time dump and import it. What say?

A one-time dump is a nice idea but it won't cover splits that occur after the day we have taken the dump. Continuously scraping it might be an issue because of copyright on moneycontrol. One time should be fine though.

**Comment by amirsultan** [comment]
Yes, one-time dump is fine. Will work for time being and its easy to handle.

**Comment by jinit24** [comment]
I am closing this issue. I have tested the code and the bug is resolved. Please take a look <a href="https://github.com/NSEDownload/NSEDownload">4.0</a>.
