### ISSUE TITLE
stocks.get_adjusted_stock still referring to old url

### ISSUE THREAD

**Issue by vishalvicky777** [NSEDownload/NSEDownload#31]
Hello,
It seems the fixed branch "jshah-fix-nse-url" is still referring to the old nse url for some of the functions.
For example:  stocks.get_adjusted_stock() is still giving TooManyRedirects Error
![image](https://user-images.githubusercontent.com/16868141/232304170-7d427b40-49a3-4ae1-842d-67b73be6a666.png)

**Comment by vishalvicky777** [comment]
The same issue holds true for _stocks.get_data()_ and _stocks.get_adjusted_data()_ combinations

**Comment by jinit24** [comment]
I've updated only: `stocks.get_data`
Check the branch's readme for an example

**Comment by alloc7260** [comment]
Use this insted : [NSE-HISTORY-SCRAPER](https://github.com/alloc7260/NSE)

**Comment by sharu0071** [comment]
Is this available for total return value of NSE Indices ?

**Comment by jinit24** [comment]
Check out the new master. @sharu0071  @vishalvicky777 @alloc7260

**Comment by sharu0071** [comment]
> Check out the new master. @sharu0071  @vishalvicky777 @alloc7260 

![PXL_20230629_173639031.MP.jpg](https://github.com/NSEDownload/NSEDownload/assets/111654959/9a83f6d5-5f92-4a60-a908-10ee66f43e7e)




This error is coming while trying to download the TRI data 

Please try again. Error has occurred
Exceeded 30 redirects

Returning empty df as complete data not received

**Comment by jinit24** [comment]
@sharu0071,
I've removed indices in the new master. Only supporting stocks for the time being. So, you are using an older version. Follow the steps on the master branch to get the latest version
