### ISSUE TITLE
IP getting blacklisted at NSE after frequent calls

### ISSUE THREAD

**Issue by ddebta** [NSEDownload/NSEDownload#34]
About 30 minutes back, around 2023-08-25 07:30 I fetched data for all Nifty50 stocks asynchronously. And since then:

```
Showing Error at 2023-08-25 08:11:31,820

Fetched url: https://www.nseindia.com/ with status code: 403 (Forbidden)

response from server:
b'
<center>
   <img alt="NSE LOGO" data-entity-type="file" data-entity-uuid="86901d97-b8dd-4dc2-8ea9-d05b32cb71ae" src="https://uat-ipo.nseindia.com/eipo/bidux/images/logo.png?1" />\n\n
   <h1 style="color: #dc3545;">Access Restricted</h1>
   \n
   <p>Your number of requests per second has exceeded the permissible threshold.<br />\nHence your IP has been restricted to access this URL/page.<br />\nPlease try accessing this page again after 10 minutes.</p>
   \n\n
   <p>However, you may continue to browse other pages of our website.<br />\nThank you for your support and understanding! <br />\nReference:0.7392017.1692930631.243ce8fe</p>
</center>
```

Also noticed your message:
```
File "C:\python-nsedownloader\env\lib\site-packages\NSEDownload\scraper.py", line 70, in fetch_url
    raise ValueError("Please try again in a minute.")
ValueError: Please try again in a minute.
```

Both 10 minutes and 1 minute are over by several fold. A simple note in README or in Instructions (anywhere) would have helped restricting me from making multiple simultaneous fetches. I would have simply placed a delay between each call, and this could be easily avoided.

Wondering whether my IP got permanently blacklisted at NSE. Its almost next to impossible to change IP_MAC_ADDRESS.

**Comment by ddebta** [comment]
Many thanks for this repo, highly appreciate it!

Coming back to this issue, after several trial-and-error safest delay between each symbol call is 5 seconds. And at-least 60 seconds delay between each session.

Fetching async is bound to get the IP dead, all calls must be made synchronously to avoid any issue.

Would request to kindly update [README](https://github.com/NSEDownload/NSEDownload#readme), so that others may avoid the same.

Thanks again!

**Comment by jinit24** [comment]
Thanks @ddebta for the analysis, please make a PR with the necessary details. I'll be happy to review and merge it

**Comment by jinit24** [comment]
[Added Section](https://github.com/NSEDownload/NSEDownload?tab=readme-ov-file#tips--tricks). Marking as done
