### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by maheshgune** [NSEDownload/NSEDownload#6]
Simple suggestions.

1) Instead of providing non-adjusted and adjusted data, will be possible to return adjusted data with a single command? That would be real helpful.

2) The output provided has date format as YYYY-MM-DD while command requires, DD-MM-YYYY format.  Can input date format can be changed to YYY-MM-DD format which is fairly standard in stock data,

This will also help a lot in programming.

**Comment by jinit24** [comment]
1. 
```
df = stocks.get_adjusted_stock(stockSymbol = 'RELIANCE', start_date = '15-9-2021', end_date = '1-10-2021')
```
I have added this function. Combines the other two

2. I have added this as well.

**Comment by maheshgune** [comment]
Do we need to update our NSEDownload module?

Thanks for helping us.

**Comment by jinit24** [comment]
Yep. You'll have to use the new version.
